<?php

use App\Support\PermalinkManager;

return [
    'groups' => [
        'general' => [
            'title' => 'General',
            'permission' => 'setting.view',
            'fields' => [
                [
                    'key' => 'site_title',
                    'label' => 'Site title',
                    'type' => 'text',
                    'default' => 'My Website',
                    'rules' => ['required','string','max:120'],
                    'hint' => 'Website name shown in title and header.',
                ],
                [
                    'key' => 'site_description',
                    'label' => 'Site description',
                    'type' => 'textarea',
                    'default' => '',
                    'rules' => ['nullable','string','max:255'],
                    'hint' => 'Site description shown in meta description.',
                ],
                [
                    'key' => 'site_keywords',
                    'label' => 'Site keywords',
                    'type' => 'textarea',
                    'default' => '',
                    'rules' => ['nullable','string','max:255'],
                    'hint' => 'Site keywords shown in keywords and description. example: keyword1, keyword2, keyword3, keyword4, keyword5, keyword6',
                ],
                [
                    'key' => 'site_email',
                    'label' => 'Site email',
                    'type' => 'email',
                    'default' => 'admin@example.com',
                    'rules' => ['nullable','email','max:120'],
                ],
                [
                    'key' => 'site_phone',
                    'label' => 'Site phone number',
                    'type' => 'text',
                    'default' => '',
                    'rules' => ['nullable','numeric','digits_between:10,15'],
                ],
                [
                    'key' => 'logo',
                    'label' => 'Logo',
                    'type' => 'image',
                    'default' => null,
                    'rules' => ['nullable','string','max:255'],
                ],
                [
                    'key' => 'site_favicon',
                    'label' => 'Favicon',
                    'type' => 'image',
                    'default' => null,
                    'rules' => ['nullable','string','max:255'],
                ],
                [
                    'key' => 'timezone',
                    'label' => 'Timezone',
                    'type' => 'select',
                    'default' => env('APP_TIMEZONE', 'Asia/Dhaka'),
                    'options' => array_combine(DateTimeZone::listIdentifiers(), DateTimeZone::listIdentifiers()),
                    'rules' => ['required','string'],
                ],
                [
                    'key' => 'date_display_format',
                    'label' => 'Top bar date format',
                    'type' => 'select',
                    'default' => 'gregorian_and_bangla',
                    'options' => [
                        'gregorian_and_bangla' => 'বাংলা ও গ্রেগরিয়ান',
                        'gregorian_only' => 'শুধু গ্রেগরিয়ান',
                    ],
                    'rules' => ['required','in:gregorian_only,gregorian_and_bangla'],
                    'hint' => 'টপ বারে তারিখ কোন ফরমেট এ দেখাবে তা নির্ধারণ করুন।',
                ],
                [
                    'key' => 'site_copyright',
                    'label' => 'Site copyright',
                    'type' => 'textarea',
                    'default' => '',
                    'rules' => ['nullable','string'],
                ],
                [
                    'key' => 'maintenance_mode',
                    'label' => 'Maintenance mode',
                    'type' => 'switch',
                    'default' => false,
                    'rules' => ['boolean'],
                    'hint' => 'This site is currently in maintenance mode.',
                ],
                [
                    'key' => 'hippo_api_key',
                    'label' => 'Image hippo API Key',
                    'type' => 'text',
                    'default' => '',
                    'placeholder' => 'API Key',
                    'rules' => ['nullable', 'string', 'max:190'],
                ],
                [
                    'key' => 'image_optimize_query',
                    'label' => 'Image optimization query',
                    'type' => 'text',
                    'default' => 'rect=0,0,6720,4480&w=1200&auto=format,compress&fmt=avif',
                    'placeholder' => 'rect=0,0,6720,4480&w=1200&auto=format,compress&fmt=avif',
                    'rules' => ['nullable', 'string', 'max:255'],
                    'hint' => 'Optional query string appended to image URLs for resizing/formatting via a CDN or proxy.',
                ],
            ],
        ],
        'reading' => [
            'title' => 'Reading',
            'permission' => 'setting.view',
            'fields' => [
                [
                    'key' => 'homepage_display',
                    'label' => 'Your homepage displays',
                    'type' => 'select',
                    'default' => 'latest_posts',
                    'options' => [
                        'latest_posts' => 'Latest posts',
                        'static_page' => 'A static page',
                    ],
                    'rules' => ['required', 'in:latest_posts,static_page'],
                ],
                [
                    'key' => 'homepage_page_id',
                    'label' => 'Homepage',
                    'type' => 'page_select',
                    'default' => null,
                    'rules' => ['nullable', 'integer', 'exists:pages,id'],
                    'visible_when' => [
                        'homepage_display' => 'static_page',
                    ],
                    'hint' => 'Select the page you want to show on the front page.',
                ],
                [
                    'key' => 'posts_page_id',
                    'label' => 'Posts page',
                    'type' => 'page_select',
                    'default' => null,
                    'rules' => ['nullable', 'integer', 'exists:pages,id'],
                    'visible_when' => [
                        'homepage_display' => 'static_page',
                    ],
                    'hint' => 'Select a page to show your latest posts (optional).',
                ],
            ],
        ],
        'admin-appearance' => [
            'title' => 'Admin appearance',
            'permission' => 'setting.view',
            'fields' => [
                [
                    'key' => 'admin_logo',
                    'label' => 'Admin logo',
                    'type' => 'image',
                    'default' => null,
                    'rules' => ['nullable','string','max:255'],
                    'hint' => 'Recommended size: 200x60.',
                ],
                [
                    'key' => 'admin_logo_height',
                    'label' => 'Logo height (px)',
                    'type' => 'number',
                    'default' => 32,
                    'rules' => ['nullable','integer','min:1','max:200'],
                    'hint' => 'Set the height of the admin logo in pixels.',
                ],
                [
                    'key' => 'admin_favicon',
                    'label' => 'Admin favicon',
                    'type' => 'image',
                    'default' => null,
                    'rules' => ['nullable','string','max:255'],
                ],
                [
                    'key' => 'admin_favicon_type',
                    'label' => 'Admin favicon type',
                    'type' => 'select',
                    'default' => 'ico',
                    'options' => [
                        'ico' => 'ICO',
                        'png' => 'PNG',
                        'svg' => 'SVG',
                    ],
                    'rules' => ['nullable','string','in:ico,png,svg'],
                ],
                [
                    'key' => 'admin_login_background',
                    'label' => 'Login screen background',
                    'type' => 'image',
                    'default' => null,
                    'rules' => ['nullable','string','max:255'],
                    'hint' => 'Recommended size: 1366 x 768.',
                ],
                [
                    'key' => 'admin_title',
                    'label' => 'Admin title',
                    'type' => 'text',
                    'default' => 'Laravel Blog Admin',
                    'rules' => ['nullable','string','max:120'],
                ],
                [
                    'key' => 'admin_primary_font',
                    'label' => 'Primary font',
                    'type' => 'select',
                    'default' => 'Inter',
                    'options' => [
                        'Inter' => 'Inter',
                        'Roboto' => 'Roboto',
                        'Poppins' => 'Poppins',
                        'Open Sans' => 'Open Sans',
                    ],
                    'rules' => ['nullable','string','max:80'],
                ],
                [
                    'key' => 'admin_primary_color',
                    'label' => 'Primary color (light mode)',
                    'type' => 'color',
                    'default' => '#2563eb',
                    'rules' => ['nullable','string','max:7'],
                ],
                [
                    'key' => 'admin_secondary_color',
                    'label' => 'Secondary color (light mode)',
                    'type' => 'color',
                    'default' => '#475569',
                    'rules' => ['nullable','string','max:7'],
                ],
                [
                    'key' => 'admin_heading_color',
                    'label' => 'Heading color (light mode)',
                    'type' => 'color',
                    'default' => '#0f172a',
                    'rules' => ['nullable','string','max:7'],
                ],
                [
                    'key' => 'admin_text_color',
                    'label' => 'Text color (light mode)',
                    'type' => 'color',
                    'default' => '#334155',
                    'rules' => ['nullable','string','max:7'],
                ],
                [
                    'key' => 'admin_link_color',
                    'label' => 'Link color (light mode)',
                    'type' => 'color',
                    'default' => '#2563eb',
                    'rules' => ['nullable','string','max:7'],
                ],
                [
                    'key' => 'admin_link_hover_color',
                    'label' => 'Link hover color (light mode)',
                    'type' => 'color',
                    'default' => '#1d4ed8',
                    'rules' => ['nullable','string','max:7'],
                ],
                [
                    'key' => 'admin_primary_color_dark',
                    'label' => 'Primary color (dark mode)',
                    'type' => 'color',
                    'default' => '#60a5fa',
                    'rules' => ['nullable','string','max:7'],
                ],
                [
                    'key' => 'admin_secondary_color_dark',
                    'label' => 'Secondary color (dark mode)',
                    'type' => 'color',
                    'default' => '#94a3b8',
                    'rules' => ['nullable','string','max:7'],
                ],
                [
                    'key' => 'admin_heading_color_dark',
                    'label' => 'Heading color (dark mode)',
                    'type' => 'color',
                    'default' => '#f8fafc',
                    'rules' => ['nullable','string','max:7'],
                ],
                [
                    'key' => 'admin_text_color_dark',
                    'label' => 'Text color (dark mode)',
                    'type' => 'color',
                    'default' => '#e2e8f0',
                    'rules' => ['nullable','string','max:7'],
                ],
                [
                    'key' => 'admin_link_color_dark',
                    'label' => 'Link color (dark mode)',
                    'type' => 'color',
                    'default' => '#93c5fd',
                    'rules' => ['nullable','string','max:7'],
                ],
                [
                    'key' => 'admin_link_hover_color_dark',
                    'label' => 'Link hover color (dark mode)',
                    'type' => 'color',
                    'default' => '#bfdbfe',
                    'rules' => ['nullable','string','max:7'],
                ],
                [
                    'key' => 'admin_language',
                    'label' => 'Admin language',
                    'type' => 'select',
                    'default' => config('app.locale'),
                    'options' => [
                        'en' => 'English - en',
                        'bn' => 'Bangla - bn',
                    ],
                    'rules' => ['nullable','string','max:10'],
                ],
                [
                    'key' => 'admin_language_direction',
                    'label' => 'Admin language direction',
                    'type' => 'select',
                    'default' => 'ltr',
                    'options' => [
                        'ltr' => 'Left to Right',
                        'rtl' => 'Right to Left',
                    ],
                    'rules' => ['nullable','string','in:ltr,rtl'],
                ],
                [
                    'key' => 'admin_rich_editor',
                    'label' => 'Rich editor',
                    'type' => 'select',
                    'default' => 'ckeditor',
                    'options' => [
                        'ckeditor' => 'CKEditor',
                        'tinymce' => 'TinyMCE',
                    ],
                    'rules' => ['nullable','string','in:ckeditor,tinymce'],
                ],
                [
                    'key' => 'admin_layout',
                    'label' => 'Layout',
                    'type' => 'select',
                    'default' => 'vertical',
                    'options' => [
                        'vertical' => 'Vertical',
                        'horizontal' => 'Horizontal',
                    ],
                    'rules' => ['nullable','string','in:vertical,horizontal'],
                ],
                [
                    'key' => 'admin_container_width',
                    'label' => 'Container width',
                    'type' => 'select',
                    'default' => 'default',
                    'options' => [
                        'default' => 'Default',
                        'large' => 'Large',
                        'full' => 'Full',
                    ],
                    'rules' => ['nullable','string','in:default,large,full'],
                ],
                [
                    'key' => 'admin_show_menu_item_icon',
                    'label' => 'Show menu item icon',
                    'type' => 'switch',
                    'default' => true,
                    'rules' => ['boolean'],
                    'hint' => 'Display icons next to admin sidebar items.',
                ],
                [
                    'key' => 'admin_show_admin_bar',
                    'label' => 'Show admin bar for logged-in admins',
                    'type' => 'switch',
                    'default' => true,
                    'rules' => ['boolean'],
                    'hint' => 'Show admin bar even on the front site.',
                ],
                [
                    'key' => 'admin_show_guidelines',
                    'label' => 'Show guidelines',
                    'type' => 'switch',
                    'default' => false,
                    'rules' => ['boolean'],
                ],
                [
                    'key' => 'admin_custom_css',
                    'label' => 'Custom CSS',
                    'type' => 'textarea',
                    'default' => '',
                    'rules' => ['nullable','string'],
                    'hint' => 'CSS that will be injected into the admin panel.',
                ],
                [
                    'key' => 'admin_header_js',
                    'label' => 'Header JS',
                    'type' => 'textarea',
                    'default' => '',
                    'rules' => ['nullable','string'],
                    'hint' => 'JavaScript added inside the <head> tag.',
                ],
                [
                    'key' => 'admin_body_js',
                    'label' => 'Body JS',
                    'type' => 'textarea',
                    'default' => '',
                    'rules' => ['nullable','string'],
                    'hint' => 'JavaScript added before the closing </body> tag.',
                ],
                [
                    'key' => 'admin_footer_js',
                    'label' => 'Footer JS',
                    'type' => 'textarea',
                    'default' => '',
                    'rules' => ['nullable','string'],
                    'hint' => 'JavaScript added at the end of the page.',
                ],
            ],
        ],

        'permalinks' => [
            'title' => 'Permalinks',
            'fields' => [

                [
                    'key' => 'permalink_structure',
                    'type' => 'permalink_structure',
                    'label' => 'Permalink structure',
                    'default' => PermalinkManager::DEFAULT_STRUCTURE,
                    'rules' => ['required', 'string'],
                    'hint' => 'SEO friendly URL structure choose করুন।',
                ],

                [
                    'key' => 'custom_permalink_structure',
                    'type' => 'text',
                    'label' => 'Custom structure',
                    'default' => '',
                    'rules' => ['nullable', 'string', 'max:190'],
                    'hint' => 'Example: news/%year%/%postname%',
                    'visible_when' => [
                        'permalink_structure' => 'custom',
                    ],
                ],

                [
                    'key' => 'post_url_extension',
                    'type' => 'text',
                    'label' => 'Post URL extension',
                    'default' => '',
                    'rules' => ['nullable', 'string', 'max:20', 'regex:/^\\.[a-z0-9]+$/i'],
                    'hint' => 'Example: .html (খালি রাখলে extension থাকবে না)',
                ],

                [
                    'key' => 'category_slug_prefix',
                    'type' => 'text',
                    'label' => 'Category URL base',
                    'default' => '',
                    'rules' => ['nullable', 'string', 'max:50'],
                    'hint' => 'Example: category (খালি রাখলে prefix থাকবে না)',
                ],

                [
                    'key' => 'tag_slug_prefix',
                    'type' => 'text',
                    'label' => 'Tag URL base',
                    'default' => '',
                    'rules' => ['nullable', 'string', 'max:50'],
                    'hint' => 'Example: tags (খালি রাখলে prefix থাকবে না)',
                ],
                [
                    'key'     => 'page_slug_prefix',
                    'label'   => 'Page URL base',
                    'type'    => 'text',
                    'default' => '',
                    'rules'   => ['nullable', 'regex:/^[a-z0-9\\-]+$/'],
                    'hint' => 'Example: page, info, docs (খালি রাখলে prefix থাকবে না)',
                ],

                [
                    'key' => 'category_url_extension',
                    'type' => 'text',
                    'label' => 'Category URL extension',
                    'default' => '',
                    'rules' => ['nullable', 'string', 'max:20', 'regex:/^\\.[a-z0-9]+$/i'],
                    'hint' => 'Example: .html (খালি রাখলে extension থাকবে না)',
                ],

                [
                    'key' => 'tag_url_extension',
                    'type' => 'text',
                    'label' => 'Tag URL extension',
                    'default' => '',
                    'rules' => ['nullable', 'string', 'max:20', 'regex:/^\\.[a-z0-9]+$/i'],
                    'hint' => 'Example: .html (খালি রাখলে extension থাকবে না)',
                ],

                [
                    'key' => 'page_url_extension',
                    'type' => 'text',
                    'label' => 'Page URL extension',
                    'default' => '',
                    'rules' => ['nullable', 'string', 'max:20', 'regex:/^\\.[a-z0-9]+$/i'],
                    'hint' => 'Example: .html (খালি রাখলে extension থাকবে না)',
                ],

                [
                    'key' => '_permalink_preview',
                    'type' => 'permalink_preview', // ✅ computed preview
                    'label' => 'Sample URL',
                ],

            ],
        ],
        'seo' => [
            'title' => 'SEO',
            'permission' => 'setting.view',
            'fields' => [
                ['key'=>'seo_default_title','label'=>'Default title','type'=>'text','default'=>'My Site','rules'=>['nullable','string','max:255']],
                ['key'=>'seo_default_description','label'=>'Default description','type'=>'textarea','default'=>'','rules'=>['nullable','string','max:500']],
                ['key'=>'seo_default_og_image','label'=>'Default OG image','type'=>'image','default'=>null,'rules'=>['nullable','string','max:255']],
                ['key'=>'seo_indexing','label'=>'Allow indexing','type'=>'switch','default'=>true,'rules'=>['boolean']],
            ],
        ],
        'cache' => [
            'title'      => 'Cache Configuration',
            'permission' => 'setting.view',
            'fields'     => [
                [
                    'key'     => 'cache_admin_menu',
                    'label'   => 'Cache Admin Menu',
                    'type'    => 'switch',
                    'default' => true,
                    'rules'   => ['boolean'],
                    'hint'    => 'Enable to speed up dashboard navigation by caching the admin menu structure.',
                ],
                [
                    'key'     => 'cache_front_menus',
                    'label'   => 'Cache Frontend Menus',
                    'type'    => 'switch',
                    'default' => true,
                    'rules'   => ['boolean'],
                    'hint'    => 'Enable to cache navigation menus rendered on the frontend for better performance.',
                ],
                [
                    'key'     => 'cache_user_avatar',
                    'label'   => 'Cache User Avatar',
                    'type'    => 'switch',
                    'default' => false,
                    'rules'   => ['boolean'],
                    'hint'    => 'Generate and store user avatar thumbnails locally until the user updates them.',
                ],
                [
                    'key'     => 'cache_shortcodes',
                    'label'   => 'Cache Shortcodes',
                    'type'    => 'switch',
                    'default' => true,
                    'rules'   => ['boolean'],
                    'hint'    => 'Enable caching for shortcode-rendered blocks to reduce processing time.',
                ],
                [
                    'key'     => 'cache_shortcode_blocks',
                    'label'   => 'Shortcode Cache Limit (Blocks)',
                    'type'    => 'number',
                    'default' => 5,
                    'rules'   => ['nullable', 'integer', 'min:1'],
                    'hint'    => 'Maximum number of shortcode blocks to cache simultaneously.',
                ],
                [
                    'key'     => 'cache_widgets',
                    'label'   => 'Cache Widgets',
                    'type'    => 'switch',
                    'default' => true,
                    'rules'   => ['boolean'],
                    'hint'    => 'Enable caching for homepage widget data to improve load speed.',
                ],
                [
                    'key'     => 'reset_cache_on_data_change',
                    'label'   => 'Auto-Clear Cache on Update',
                    'type'    => 'switch',
                    'default' => true,
                    'rules'   => ['boolean'],
                    'hint'    => 'Automatically clear relevant caches when posts, categories, pages, or menus are created or updated.',
                ],
                [
                    'key'     => 'cache_time',
                    'label'   => 'Global Cache Lifetime (Minutes)',
                    'type'    => 'number',
                    'default' => 60,
                    'rules'   => ['required', 'integer', 'min:0'],
                    'hint'    => 'The default duration (in minutes) for general caches like menus and widgets.',
                ],
                [
                    'key'     => 'sitemap_cache_time',
                    'label'   => 'Sitemap Cache Lifetime (Minutes)',
                    'type'    => 'number',
                    'default' => 60,
                    'rules'   => ['required', 'integer', 'min:0'],
                    'hint'    => 'The duration (in minutes) to keep the XML sitemap cached before regenerating.',
                ],
            ],
        ],
    ],
];
